### ISSUE TITLE
Errno::ENOENT (No such file or directory @ rb_sysopen - {RAILS_PATH}/tmp/data/meta_request/xxx.json)

### ISSUE THREAD

**Issue by durnin** [dejan/rails_panel#145]
Using ruby '2.5.1', 'rails', '~> 5.2.0' I'm getting the following stack trace, multiple times (Rails Panel works, but server get's plagued with this exceptions):

```
Errno::ENOENT (No such file or directory @ rb_sysopen - {RAILS_PATH}/tmp/data/meta_request/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.json):
  
meta_request (0.6.0) lib/meta_request/storage.rb:16:in `read'
meta_request (0.6.0) lib/meta_request/storage.rb:16:in `read'
meta_request (0.6.0) lib/meta_request/middlewares/meta_request_handler.rb:20:in `events_json'
meta_request (0.6.0) lib/meta_request/middlewares/meta_request_handler.rb:11:in `call'
scout_apm (2.4.14) lib/scout_apm/instant/middleware.rb:53:in `call'
scout_apm (2.4.14) lib/scout_apm/middleware.rb:20:in `call'
rack-attack (5.4.0) lib/rack/attack.rb:174:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
airbrake (7.3.4) lib/airbrake/rack/middleware.rb:48:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
rack-contrib (2.0.1) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.6.0) lib/meta_request/middlewares/headers.rb:16:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```
As you can see from stack we use other middleware like:
- scout_apm
- rack-attack
- rack-rewrite
- rack-timeout
- web-console
- airbrake
But nothing unusual about those. Any help to remove this noise appreciated.

**Comment by gogiel** [comment]
Might be related to https://github.com/dejan/rails_panel/issues/94

**Comment by gogiel** [comment]
Settings higher `storage_pool_size` should fix that.

However it still shouldn't raise this kind of raw issue.

Task: replace raw `Errno` exception with an user-friendly message referring to potential issue with `storage_pool_size`.

**Comment by bartimez** [comment]
I'm seeing this as well - I added an initializer to my project that sets the storage pool size all the way to 200, but am still seeing: 

```Started GET "/__meta_request/67f5d738-c1da-4741-aa0a-dddafa3d6046.json" for 127.0.0.1 at 2020-06-11 09:37:54 -0500
Started GET "/__meta_request/ef95ee61-74fb-4e44-92af-bba5d5c1b096.json" for ::1 at 2020-06-11 09:37:54 -0500

Errno::ENOENT (No such file or directory @ rb_sysopen - {RAILS_PATH}/tmp/data/meta_request/xxxxxxxx.json):

meta_request (0.7.2) lib/meta_request/storage.rb:16:in `read'
meta_request (0.7.2) lib/meta_request/storage.rb:16:in `read'
meta_request (0.7.2) lib/meta_request/middlewares/meta_request_handler.rb:20:in `events_json'
meta_request (0.7.2) lib/meta_request/middlewares/meta_request_handler.rb:11:in `call'
p3p (2.0.0) lib/p3p/middleware.rb:9:in `call'
remotipart (572f45d234a8) lib/remotipart/middleware.rb:32:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.9) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.9) lib/rack/etag.rb:25:in `call'
rack (2.0.9) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.9) lib/rack/head.rb:12:in `call'
actionpack (6.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.9) lib/rack/session/abstract/id.rb:259:in `context'
rack (2.0.9) lib/rack/session/abstract/id.rb:253:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
airbrake (10.0.4) lib/airbrake/rack/middleware.rb:34:in `call!'
airbrake (10.0.4) lib/airbrake/rack/middleware.rb:23:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.2) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.2) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.2) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.2) lib/web_console/middleware.rb:17:in `call'
rack-contrib (2.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.7.2) lib/meta_request/middlewares/headers.rb:16:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `call'
silencer (1.0.1) lib/silencer/rails/logger.rb:41:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.9) lib/rack/method_override.rb:22:in `call'
rack (2.0.9) lib/rack/runtime.rb:22:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.9) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
rack-mini-profiler (1.1.6) lib/mini_profiler/profiler.rb:296:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
railties (6.0.2.2) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.2.2) lib/rails/railtie.rb:190:in `method_missing'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
logging (2.2.2) lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```
